#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${ROOT_DIR}/codex_contract.yml"

collect_functions() {
  local file="$1"
  grep -E '^[a-zA-Z_][a-zA-Z0-9_]*\(\)[[:space:]]*\{' "$file" | \
    sed -E 's/\(\).*//' | \
    sed -E 's/^[[:space:]]+//;s/[[:space:]]+$//' | \
    sort -u
}

{
  echo "# Autogenerated contract"
  echo "modules:"
  for section in modules utils; do
    echo "  ${section}:"
    for file in "${ROOT_DIR}/${section}"/*.sh; do
      [ -e "$file" ] || continue
      echo "    $(basename "$file"):" 
      while IFS= read -r fn; do
        echo "      - ${fn}"
      done < <(collect_functions "$file")
    done
  done
  echo "  bootstrap:" 
  echo "    bootstrap_compat.sh:"
  while IFS= read -r fn; do
    echo "      - ${fn}"
  done < <(collect_functions "${ROOT_DIR}/bootstrap_compat.sh")
  echo "scripts:" 
  echo "  process_protective_v1.6.sh:"
  while IFS= read -r fn; do
    echo "    - ${fn}"
  done < <(collect_functions "${ROOT_DIR}/process_protective_v1.6.sh")
} > "$OUTPUT_FILE"

echo "Contract extracted to ${OUTPUT_FILE}"
