name: Uniclon CI Validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Bash syntax
        run: bash -n process_protective_v1.6.sh

      - name: Test Python FSM
        run: python3 -m unittest discover -s tests -p "test_*.py"
